### ISSUE TITLE
transactionCurrency

### ISSUE THREAD

**Issue by affanhashone** [xDAnkit/react-native-google-pay-tez#1]
IS USD Accepted

**Comment by xDAnkit** [comment]
@affanhashone - Currently this package is only supporting **"INR".** Since it is based of "Google Pay(Tez) for india" which is specifically designed for Indian audience. 

This package is specifically targetting this app by Google https://play.google.com/store/apps/details?id=com.google.android.apps.nbu.paisa.user&hl=en_IN

**Comment by xDAnkit** [comment]
Closing this issue since **"INR"** is the only one which is supported as of now.

**Comment by affanhashone** [comment]
If possible Please convert to global google google pay.

Thanks.

**Comment by xDAnkit** [comment]
Actually , as of now there are different services and apps are there for accessing google pay services Based on origin. In India they have rolled out a different application which was formerly named as “Google Tez” later they renamed that as “Google Pay” .

I’ll look for the alternative solution To make this app global. meanwhile you can have a look over here to use “Google Pay” for USD 

https://medium.com/@flutterhackserices/integrate-google-pay-android-pay-into-react-native-mobile-app-4701198e22a9

**Comment by affanhashone** [comment]
@xDAnkit  I implemented  from another Method, It was a suggestion to make it global. Thanks

**Comment by xDAnkit** [comment]
Sure . I’ll look into it. Thank you so much for your valuable suggestion.
